### ISSUE TITLE
可以增加个广告功能吗？

### ISSUE THREAD

**Issue by BOOMBOOMTom** [NJHu/iOSProject#10]
想向楼主学习一下广告的写法，就是能加载image、gif、视频。能提前缓存以后规定日期内展示的image、gif、视频。因为每次app启动时候，如果在启动的时候下载图片、gif、视频，肯定会有延迟，体验不佳，想提前缓存，并且根据需要展示的日期，自动更换图片、gif、视频。向想楼主学习。

**Comment by NJHu** [comment]
里边的启动广告不就是的吗 ?

**Comment by BOOMBOOMTom** [comment]
谢谢楼主！感谢！
