### ISSUE TITLE
project run failed？

### ISSUE THREAD

**Issue by taohonghui** [NJHu/iOSProject#11]
项目是我下载的 并没有拉取  因为clone速度太慢了
我第一次运行代码是运行在虚拟设备 出现的错误如下
![image](https://user-images.githubusercontent.com/22534369/37831884-e2de70ba-2ee1-11e8-9fda-4e4c52ee93bc.png)

不知道是不是我需要执行一些其他的代码来处理

**Comment by NJHu** [comment]
pod install 下试试

影伴人久
