### ISSUE TITLE
TZImagePickerController三方使用报错

### ISSUE THREAD

**Issue by caicai0713** [NJHu/iOSProject#16]
代码中多次重复出现TZLocationManager的startLocationWithSuccessBlock方法报错；
同样也多次出现TZImageManager的getCameraRollAlbum:NO allowPickingImage:YES completion:报错pod更新后，依然出现类似错误。
<img width="1078" alt="2018-04-19 10 19 44" src="https://user-images.githubusercontent.com/16091986/38979721-903f4a84-43ed-11e8-973c-9530fa803034.png">
<img width="1036" alt="2018-04-19 10 20 02" src="https://user-images.githubusercontent.com/16091986/38979738-9b957b4c-43ed-11e8-9aa4-b9809c0c17c0.png">

**Comment by Brances** [comment]
遇到相同的错误

**Comment by NJHu** [comment]
感谢关注, 已解决, 谢谢
