### ISSUE TITLE
Pod 文件管理优化

### ISSUE THREAD

**Issue by AAChartModel** [NJHu/iOSProject#19]
你这里的pod 导入的第三方库没有添加到 gitignore 当中,导致的结果就是以后每次你更新第三方库, Git 都会跟踪记录,导致项目文件的 Git 整个体积的膨胀.

**Comment by NJHu** [comment]
- 这个建议非常好, 谢谢, 已经做相关优化
- [脚本](https://github.com/NJHu/iOSProject/blob/master/iOSProject/deletePodsTrack.sh)

- 谢谢 [AAChartModel](https://github.com/AAChartModel)
