### ISSUE TITLE
电子书阅读

### ISSUE THREAD

**Issue by LemonTreeQ** [NJHu/iOSProject#21]
可以接一个电子书阅读的，类似多看电子书阅读页面类似的，目前做过电子书阅读，但做出的效果远远不足，可以支持epub、txt等文件的阅读

**Comment by NJHu** [comment]
-  抱歉哈, 涉猎实在有限, 请移步其它 demo 

- 谢谢 [LemonTreeQ](https://github.com/LemonTreeQ)
