### ISSUE TITLE
语音转文字

### ISSUE THREAD

**Issue by dzhlch** [NJHu/iOSProject#22]
录入时比较麻烦，能否做一个类似微信按住说话的功能，说完以后直接把语音转成汉字放到录入框中

**Comment by NJHu** [comment]
- 建议您参考其他的 demo 哈

- 谢谢 [dzhlch](https://github.com/dzhlch)

**Comment by shangmeng** [comment]
你好，你这里有声波通讯的功能吗




| |
hyh2653164853
邮箱：hyh2653164853@163.com
|

签名由 网易邮箱大师 定制

在2018年06月16日 10:45，Nemo 写道：

Closed #22.
