### ISSUE TITLE
关于欢迎页增加设置入口选项

### ISSUE THREAD

**Issue by Michaelyb520** [NJHu/iOSProject#23]
1. 欢迎页最好可以增加一个pageControl的颜色设置入口（当前和高亮）；
2. 有时可能不需要广告页，去掉广告后，又希望欢迎页也有倒计时选项（像广告页可以几秒后可消失），最好也给一个设置入口；

由于是一个单对象，相信加上这几个设置入口，不是很费劲~~~

**Comment by NJHu** [comment]
- 不是很费劲就需要用的时候加吧....

- 谢谢[Michaelyb520](https://github.com/Michaelyb520)
