### ISSUE TITLE
哈哈 不知道你为什么每个VC的返回按钮都重复写那段UI代码和点击事件，而不是封装在基类里面，需要特别定制返回页面和UI的时候才去重写这个按钮？

### ISSUE THREAD

**Issue by bb5201314** [NJHu/iOSProject#24]
哈哈 不知道你为什么每个VC的返回按钮都重复写那段UI代码和点击事件，而不是封装在基类里面，需要特别定制返回页面和UI的时候才去重写这个按钮？

**Comment by NJHu** [comment]
- 感谢关注
- 这段代码确实重复.....
- 在后续编码中会注意这个问题, 参考[swiftProject](https://github.com/NJHu/swiftProject)


- 感谢[bb5201314](https://github.com/bb5201314)提出的建议, 谢谢

**Comment by shangmeng** [comment]
什么东西啊，不太懂




| |
hyh2653164853
邮箱：hyh2653164853@163.com
|

签名由 网易邮箱大师 定制

在2018年06月16日 10:42，Nemo 写道：

感谢关注

这段代码确实重复.....

在后续编码中会注意这个问题, 参考swiftProject

感谢bb5201314提出的建议, 谢谢
