### ISSUE TITLE
总觉得作为demo来说 每个类之间的封装有点过多了 想找一个功能command了好久。作为程序来讲复用性倒是不错。

### ISSUE THREAD

**Issue by asiuvxmcn** [NJHu/iOSProject#25]

**Comment by NJHu** [comment]
- 感谢关注
- 也考虑这个问题, 继承的确实有点多......懒得修复了
- 在后续编码中会注意这个问题, 参考[swiftProject](https://github.com/NJHu/swiftProject)


- 感谢[asiuvxmcn](https://github.com/asiuvxmcn)提出的建议, 谢谢
