### ISSUE TITLE
uitableview怎么拖动section啊  让分组重新排序

### ISSUE THREAD

**Issue by hlxj2030** [NJHu/iOSProject#3]

**Comment by hua16** [comment]
https://www.jianshu.com/p/639705862db2 希望对你有所帮助

**Comment by NJHu** [comment]
- 感谢[hlxj2030](https://github.com/hlxj2030)提出问题, 
  - 可以参考 iOSProject 里边拖动 cell 的移动 demo

- 感谢[hua16](https://github.com/hua16)提出更好的解决方案
