### ISSUE TITLE
打不开， pod 红的，楼主缺少文件

### ISSUE THREAD

**Issue by HYJFromQc** [NJHu/iOSProject#33]
打不开， pod 红的

**Comment by 923266908** [comment]
[!] /usr/local/bin/git clone https://github.com/ccgus/fmdb.git /var/folders/80/tttbth652b15qb18_m682dn40000gp/T/d20181029-4180-gh6ne4 --template= --single-branch --depth 1 --branch 2.7.2

Cloning into '/var/folders/80/tttbth652b15qb18_m682dn40000gp/T/d20181029-4180-gh6ne4'...
fatal: unable to access 'https://github.com/ccgus/fmdb.git/': Empty reply from server

**Comment by NJHu** [comment]
pod update 命令
