### ISSUE TITLE
运行报错 

### ISSUE THREAD

**Issue by hyz240** [NJHu/iOSProject#45]
No account for team "44HDC9YG72".

No profiles for 'github.com.njhu.iosproject' were found

![image](https://user-images.githubusercontent.com/24807339/50272318-56c45100-0472-11e9-91bd-8212dbb930a8.png)

**Comment by hyz240** [comment]
请问如何修改？

**Comment by HellowjingQiu** [comment]
模拟器可以直接搞, 真机改一下BundleID
