### ISSUE TITLE
iOSProject.debug.xcconfig: unable to open file

### ISSUE THREAD

**Issue by HearWindS** [NJHu/iOSProject#46]
`error: /Users/m/Developer/iOSProject-master/iOSProject/Pods/Target Support Files/Pods-iOSProject/Pods-iOSProject.debug.xcconfig: unable to open file (in target "iOSProject" in project "iOSProject") (in target 'iOSProject')`

你好！打扰一下，想学习你的项目，这个要pod install么？一打开项目会出现这个，请问这是什么情况？

**Comment by JWong1105** [comment]
一样的问题， pod install 也无法解决，请问你是怎么处理的呢，谢谢
