### ISSUE TITLE
Apple LLVM 9.0 Error

### ISSUE THREAD

**Issue by alldev0825** [NJHu/iOSProject#5]
On Xcode 9.2 there is one issue when building this project:
-fobjc-weak is not supported on the current deployment target
How to resolve this error?
![webwxgetmsgimg](https://user-images.githubusercontent.com/19334758/35796426-84c20df6-0a2a-11e8-9256-c95f31abe1bc.jpg)

**Comment by HolmesZhao** [comment]
版本切换到5.0以上就可以了, 这个 asi 支持4.0的

**Comment by NJHu** [comment]
感谢 [HolmesZhao](https://github.com/HolmesZhao) 同志
一直没找到方法解决呢......
感谢[alldev0825](https://github.com/alldev0825)提出问题.
