### ISSUE TITLE
直接下载完成后,工程的tools文件夹缺少文件

### ISSUE THREAD

**Issue by FrankChung1121** [NJHu/iOSProject#6]
直接下载完成后,工程的tools文件夹缺少文件,根本无法运行起来,重新pod install以后也不行

**Comment by NJHu** [comment]
把 tools 文件夹截图看看
![image](https://user-images.githubusercontent.com/18454795/36768679-4fc5fe06-1c7b-11e8-906e-7d7b03e52982.png)

**Comment by FrankChung1121** [comment]
之前是preview3里面的MJDownload文件不存在,我更新本地仓库后重新下载就可以了
