### ISSUE TITLE
求助大神

### ISSUE THREAD

**Issue by 1253504781** [NJHu/iOSProject#7]
大神可以仿写个‘即刻’的吗

**Comment by NJHu** [comment]
- 抱歉这么久才回复您, 感谢您支持本项目
- 我也不是大神哦,很多不会的地方, 这个项目只是基础知识的积累和回顾
- 至于仿写即刻 App, 最近公司项目比较赶, 实在没时间, 抱歉. 
- 支持您自己仿写即刻App, 您也可以从中学到些知识, 
ps: 如果过程中遇到问题, 欢迎一起探讨.
